"""
100 Public Domain & General Wisdom Quotes for DataDealers
"""

QUOTES = [
    {"text": "No man ever steps in the same river twice, for it's not the same river and he's not the same man.", "author": "Heraclitus"},
    {"text": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "author": "Aristotle"},
    {"text": "The only true wisdom is in knowing you know nothing.", "author": "Socrates"},
    {"text": "In the middle of difficulty lies opportunity.", "author": "Albert Einstein"},
    {"text": "Simplicity is the ultimate sophistication.", "author": "Leonardo da Vinci"},
    {"text": "The unexamined life is not worth living.", "author": "Socrates"},
    {"text": "It is not that we have a short time to live, but that we waste a lot of it.", "author": "Seneca"},
    {"text": "He who has a why to live can bear almost any how.", "author": "Friedrich Nietzsche"},
    {"text": "Knowing yourself is the beginning of all wisdom.", "author": "Aristotle"},
    {"text": "The mind is everything. What you think you become.", "author": "Buddha"},
    {"text": "The journey of a thousand miles begins with a single step.", "author": "Lao Tzu"},
    {"text": "Happiness depends upon ourselves.", "author": "Aristotle"},
    {"text": "Mastering others is strength. Mastering yourself is true power.", "author": "Lao Tzu"},
    {"text": "You have power over your mind - not outside events. Realize this, and you will find strength.", "author": "Marcus Aurelius"},
    {"text": "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", "author": "Marcus Aurelius"},
    {"text": "The best revenge is to be unlike him who performed the injury.", "author": "Marcus Aurelius"},
    {"text": "Waste no more time arguing about what a good man should be. Be one.", "author": "Marcus Aurelius"},
    {"text": "Luck is what happens when preparation meets opportunity.", "author": "Seneca"},
    {"text": "If a man knows not which port he sails to, no wind is favorable.", "author": "Seneca"},
    {"text": "Difficulties strengthen the mind, as labor does the body.", "author": "Seneca"},
    {"text": "Change your thoughts and you change your world.", "author": "Norman Vincent Peale"},
    {"text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson"},
    {"text": "Everything has beauty, but not everyone sees it.", "author": "Confucius"},
    {"text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius"},
    {"text": "Our greatest glory is not in never falling, but in rising every time we fall.", "author": "Confucius"},
    {"text": "What you do not want done to yourself, do not do to others.", "author": "Confucius"},
    {"text": "He who knows, does not speak. He who speaks, does not know.", "author": "Lao Tzu"},
    {"text": "When you are content to be simply yourself and don't compare or compete, everyone will respect you.", "author": "Lao Tzu"},
    {"text": "Great acts are made up of small deeds.", "author": "Lao Tzu"},
    {"text": "An unexamined idea is like an unsharpened pencil — useless for fine work.", "author": "Unknown"},
    {"text": "Information is not knowledge. Knowledge is not wisdom.", "author": "Albert Einstein"},
    {"text": "Look deep into nature, and then you will understand everything better.", "author": "Albert Einstein"},
    {"text": "Life is like riding a bicycle. To keep your balance, you must keep moving.", "author": "Albert Einstein"},
    {"text": "Strive not to be a success, but rather to be of value.", "author": "Albert Einstein"},
    {"text": "The measure of intelligence is the ability to change.", "author": "Albert Einstein"},
    {"text": "Genius is one percent inspiration and ninety-nine percent perspiration.", "author": "Thomas Edison"},
    {"text": "I have not failed. I've just found 10,000 ways that won't work.", "author": "Thomas Edison"},
    {"text": "The future belongs to those who prepare for it today.", "author": "Malcolm X"},
    {"text": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt"},
    {"text": "It is during our darkest moments that we must focus to see the light.", "author": "Aristotle Onassis"},
    {"text": "Be kind, for everyone you meet is fighting a hard battle.", "author": "Plato"},
    {"text": "Ignorance, the root and stem of all evil.", "author": "Plato"},
    {"text": "The direction in which education starts a man will determine his future in life.", "author": "Plato"},
    {"text": "Energy is the essence of life.", "author": "Aristotle"},
    {"text": "Patience is bitter, but its fruit is sweet.", "author": "Aristotle"},
    {"text": "Quality is not an act, it is a habit.", "author": "Aristotle"},
    {"text": "Well begun is half done.", "author": "Aristotle"},
    {"text": "Wise men speak because they have something to say; fools because they have to say something.", "author": "Plato"},
    {"text": "Courage is knowing what not to fear.", "author": "Plato"},
    {"text": "To conquer oneself is the first and noblest of all victories.", "author": "Plato"},
    {"text": "Turn your wounds into wisdom.", "author": "Oprah Winfrey"},
    {"text": "Doubt is the origin of wisdom.", "author": "René Descartes"},
    {"text": "I think, therefore I am.", "author": "René Descartes"},
    {"text": "To read good books is like holding a conversation with the most eminent minds of past centuries.", "author": "René Descartes"},
    {"text": "If I have seen further it is by standing on the shoulders of Giants.", "author": "Isaac Newton"},
    {"text": "Tact is the knack of making a point without making an enemy.", "author": "Isaac Newton"},
    {"text": "Nature is pleased with simplicity. And nature is no dummy.", "author": "Isaac Newton"},
    {"text": "Science is a way of thinking much more than it is a body of knowledge.", "author": "Carl Sagan"},
    {"text": "Somewhere, something incredible is waiting to be known.", "author": "Carl Sagan"},
    {"text": "We are a way for the cosmos to know itself.", "author": "Carl Sagan"},
    {"text": "Extravagant claims require extravagant evidence.", "author": "Carl Sagan"},
    {"text": "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more.", "author": "Marie Curie"},
    {"text": "Be less curious about people and more curious about ideas.", "author": "Marie Curie"},
    {"text": "The important thing is not to stop questioning. Curiosity has its own reason for existing.", "author": "Albert Einstein"},
    {"text": "The true sign of intelligence is not knowledge but imagination.", "author": "Albert Einstein"},
    {"text": "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", "author": "Stephen Hawking"},
    {"text": "Quiet people have the loudest minds.", "author": "Stephen Hawking"},
    {"text": "Look up at the stars and not down at your feet.", "author": "Stephen Hawking"},
    {"text": "The first principle is that you must not fool yourself and you are the easiest person to fool.", "author": "Richard Feynman"},
    {"text": "I would rather have questions that can't be answered than answers that can't be questioned.", "author": "Richard Feynman"},
    {"text": "Study hard what interests you most in the most undisciplined, irreverent and original manner possible.", "author": "Richard Feynman"},
    {"text": "For a successful technology, reality must take precedence over public relations, for Nature cannot be fooled.", "author": "Richard Feynman"},
    {"text": "What I cannot create, I do not understand.", "author": "Richard Feynman"},
    {"text": "The purpose of computing is insight, not numbers.", "author": "Richard Hamming"},
    {"text": "Error is acceptable, ambiguity is not.", "author": "Data Science Proverb"},
    {"text": "Without data, you're just another person with an opinion.", "author": "W. Edwards Deming"},
    {"text": "In God we trust; all others must bring data.", "author": "W. Edwards Deming"},
    {"text": "To measure is to know.", "author": "Lord Kelvin"},
    {"text": "Errors using inadequate data are much less than those using no data at all.", "author": "Charles Babbage"},
    {"text": "The goal is to turn data into information, and information into insight.", "author": "Carly Fiorina"},
    {"text": "Data is a precious thing and will last longer than the systems themselves.", "author": "Tim Berners-Lee"},
    {"text": "Data matures like wine, applications age like fish.", "author": "James Governor"},
    {"text": "Clear thinking requires courage rather than intelligence.", "author": "Thomas Sowell"},
    {"text": "You can have data without information, but you cannot have information without data.", "author": "Daniel Keys Moran"},
    {"text": "Where there is data smoke, there is business fire.", "author": "Thomas Redman"},
    {"text": "The world is one big data problem.", "author": "Andrew McAfee"},
    {"text": "Torture the data, and it will confess to anything.", "author": "Ronald Coase"},
    {"text": "Data are just summaries of thousands of stories.", "author": "Chip Heath"},
    {"text": "Focus on the core pattern, ignore the noise.", "author": "Data Science Proverb"},
    {"text": "All models are wrong, but some are useful.", "author": "George Box"},
    {"text": "The best way to predict the future is to invent it.", "author": "Alan Kay"},
    {"text": "Simple things should be simple, complex things should be possible.", "author": "Alan Kay"},
    {"text": "First, solve the problem. Then, write the code.", "author": "John Johnson"},
    {"text": "Make it work, make it right, make it fast.", "author": "Kent Beck"},
    {"text": "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", "author": "Martin Fowler"},
    {"text": "Premature optimization is the root of all evil.", "author": "Donald Knuth"},
    {"text": "Science is what we understand well enough to explain to a computer.", "author": "Donald Knuth"},
    {"text": "Truth is much too complicated to allow anything but approximations.", "author": "John von Neumann"},
    {"text": "There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies.", "author": "C.A.R. Hoare"},
    {"text": "It always seems impossible until it's done.", "author": "Nelson Mandela"}
]
